language: go
go:
 - 1.6.3
 - 1.7.3

script:
  - go get -u ./...
  - go test -v -race -parallel 5 -coverprofile=coverage.txt -covermode=atomic ./

after_success:
  - bash <(curl -s https://codecov.io/bash)
